version: '3.9'

services:
  # http-app-server:
  #   build:
  #     dockerfile: dev.Dockerfile
  #     context: .
  #   networks:
  #     - http-app-network
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   expose:
  #     - "8080"
  #     - "8081"
  #   volumes:
  #     - .:/app
  #   # env_file:
  #   #   - .env

  http-demo-jaeger:
    container_name: http-demo-jaeger
    image: jaegertracing/all-in-one
    ports:
      - "4317:4317"
      - "16686:16686"
    networks:
      - http-app-network
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  http-app-network:
    driver: bridge

