// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// TranslateRequest defines model for TranslateRequest.
type TranslateRequest struct {
	SourceLocale string `json:"sourceLocale"`
	SourceText   string `json:"sourceText"`
	TargetLocale string `json:"targetLocale"`
}

// TranslateResponse defines model for TranslateResponse.
type TranslateResponse struct {
	TargetText *string `json:"targetText,omitempty"`
}

// TranslateJSONRequestBody defines body for Translate for application/json ContentType.
type TranslateJSONRequestBody = TranslateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Translate an source text from source locale to target locale
	// (POST /translate)
	Translate(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Translate converts echo context to params.
func (w *ServerInterfaceWrapper) Translate(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Translate(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/translate", wrapper.Translate)

}

type TranslateRequestObject struct {
	Body *TranslateJSONRequestBody
}

type TranslateResponseObject interface {
	VisitTranslateResponse(w http.ResponseWriter) error
}

type Translate200JSONResponse TranslateResponse

func (response Translate200JSONResponse) VisitTranslateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Translate an source text from source locale to target locale
	// (POST /translate)
	Translate(ctx context.Context, request TranslateRequestObject) (TranslateResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Translate operation middleware
func (sh *strictHandler) Translate(ctx echo.Context) error {
	var request TranslateRequestObject

	var body TranslateJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Translate(ctx.Request().Context(), request.(TranslateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Translate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(TranslateResponseObject); ok {
		return validResponse.VisitTranslateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RSvXLbMAx+FQbt6LPUZtOYqb3r1GbrdWAoKKGPIlgQSu3L6d17IGXHjpUxGwRC3w/w",
	"vYCjMVHEKBm6F2D8O2GWO+o9lsY925iDFfxZX7TnKArGUtqUgndWPMVmlylqL7snHK1WnxkH6OBT80rS",
	"1NfcXAHP87yBHrNjnxQPuhO5p2gWZeaB+gPo6AL0nsjElJBlsZFpYoc/yNmA+o17OyYtASNsQA5J6yzs",
	"4yMoeJm/x71cTn/DEMj8Iw79zdp/YvkRZY1n4Ov5eVMW7hl76H6fk24uFb8B/nNCoocdOlHmsx3kRDHj",
	"9RIqxrWpO4o7mtgENCPFHm9Wlb5h1JaPAxVgLwXoqIHYZORn71T5M3Ku52y37faLaqWE0SYPHdxu2+0t",
	"bCBZeSoaGzn6KPqpHlNdlBh8789oFP01sIf3EneR6ZXcKUhdWVHwtW0/IuTLUVZS/mtyDnMepmBOPmvC",
	"p3G0fDh3bGw0NRlGcC9mYBqPjVDCYYRMPfTSUMr5fwAAAP//l0AjRugDAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
